#! /usr/bin/env perl

use warnings;
use strict;

sub dirname {
  local($name) = @_;
  $name =~ s/\\/\//g;
  $name =~ tr/A-Z/a-z/;
  return $name;
}

$Baseline = &dirname($ENV{'DeltaBaselineDir'});
$Delta    = &dirname($ENV{'DeltaDir'});

sub catdir {
  local($a,$b) = @_;
  return $a if $b eq "";
  return $b if $a eq "";
  return "$a/$b";
}

sub files {
  local($sub) = @_;
  local($dir) = &catdir($Baseline,$sub);  
  opendir(DIR,"$dir") || (warn "Can't open $dir: $!\n", return);
  local(@filenames) = readdir(DIR);
  closedir(DIR);
  for (@filenames) {
    next if $_ eq '.';
    next if $_ eq '..';
    next if $_ eq 'RCS';
    if (-d "$dir/$_") {
      &files(&catdir($sub,$_));
    } else {
      &wanted($dir, $_);
    }
  }
}

sub wanted {
  local($dir,$file) = @_;
  printf "%s %s\n", $sub, $file;
}

sub check_dir {
  local($sub) = @_;
  local($dir) = &catdir($Delta,$sub);  
  if (-d $dir) {
    &files($sub);
  }
}

&check_dir("bin");
&check_dir("vm");
&check_dir("world");
