#! /usr/bin/env perl

use warnings;
use strict;

sub dirname {
  local($name) = @_;
  $name =~ s/\\/\//g;
  $name =~ tr/A-Z/a-z/;
  return $name;
}

$Delta = &dirname($ENV{'DeltaDir'});

sub files {
  local($dir) = @_;
  opendir(DIR,"$dir") || (warn "Can't open $dir: $!\n", return);
  local(@filenames) = readdir(DIR);
  closedir(DIR);
  for (@filenames) {
    next if $_ eq '.';
    next if $_ eq '..';
    if (-d "$dir/$_") {
      &files("$dir/$_");
    } else {
      &wanted("$dir/$_");
    }
  }
}
1 ;

sub mydelete {
  local($file) = @_;
  printf "Deleting %s\n", $file;
  unlink $file;
}

sub wanted {
  local($file) = @_;
  &mydelete($file) if $file =~ /\.bak$|\.OLD$|\.publish$|\.~$/;
}

&files("$Delta");
