#! /usr/bin/env perl

use warnings;
use strict;

open(FILES, "baseVMfiles |");
while (<FILES>) {
  chop;                     
  printf STDERR ".";
  `baseCompare $_`  if $_ !~ /prims.src$|prims.inc$/
}
