#! /usr/bin/env bash

# bash ------------------------------------------------------------------------

set -o errexit -o nounset
${BASH_DEBUG:+trap '(read -p "[${BASH_SOURCE}:${LINENO}] [${BASH_COMMAND}] ")' DEBUG}


# location --------------------------------------------------------------------

set -o errexit -o nounset
readonly _REALPATH=$(realpath "${BASH_SOURCE[ 0 ]}")
readonly _BASENAME=$(basename "${_REALPATH}")
readonly _DIRNAME=$(dirname "${_REALPATH}")
readonly _ROOT=$(dirname "${_DIRNAME}")
readonly _PREFIX=$(dirname "${_ROOT}")


# environment -----------------------------------------------------------------

export PYTHONDONTWRITEBYTECODE=1
export PYTHONPATH=${_ROOT}/src/python/main/${PYTHONPATH:+:${PYTHONPATH}}
export PYTHONPATH=${_ROOT}/lib/python/main/${PYTHONPATH:+:${PYTHONPATH}}


# execute ---------------------------------------------------------------------

readonly venv_python=${_ROOT}/.venv/bin/python
if [[ ! -L ${venv_python} ]]; then 
    err "error:  the .venv/ directory is missing."
    err " hint:  run bin/venv-create to create the .venv/ directory."
    exit 1234
fi

exec ${venv_python} "${@}"

